# This workflow builds and tests the Swift projects in the repository
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift CI
on:
  push:
    branches: [ "testing/joshua" ]
  pull_request:
    branches: [ "testing/joshua" ]
    
jobs:
# --- Job for the ImageClassifier project ---
  image-classifier:
    name: Build and Test ImageClassifier
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download models
      working-directory: ./image_classification
      run: ./RunScripts/download_models.sh

    - name: Install CocoaPods
      working-directory: ./image_classification
      run: pod install

    - name: Build ImageClassifier
      working-directory: ./image_classification
      run: >-
        xcodebuild build
        -workspace ImageClassifier.xcworkspace
        -scheme ImageClassifier
        -sdk iphonesimulator
        -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest'

    - name: Test ImageClassifier
      working-directory: ./image_classification
      run: >-
        xcodebuild test
        -workspace ImageClassifier.xcworkspace
        -scheme ImageClassifier
        -sdk iphonesimulator
        -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest'

    # --- UPLOAD THE BUILT APP ---
    # This step only runs if the build and tests succeed.
    - name: Upload App Artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ImageClassifierApp
        path: image_classification/DerivedData/Build/Products/Debug-iphonesimulator/ImageClassifier.app

    # --- UPLOAD THE TEST RESULTS ---
    # This step runs REGARDLESS of whether the tests passed or failed.
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ImageClassifierTestResults
        path: /Users/runner/Library/Developer/Xcode/DerivedData/ImageClassifier-*/Logs/Test/*.xcresult

  # --- Job for the ObjectDetector project ---
  object-detector:
    name: Build and Test ObjectDetector
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download models
      working-directory: ./object_detection
      run: ./RunScripts/download_models.sh

    - name: Install CocoaPods
      working-directory: ./object_detection
      run: pod install

    - name: Build ObjectDetector
      working-directory: ./object_detection
      run: >-
        xcodebuild build
        -workspace ObjectDetector.xcworkspace
        -scheme ObjectDetector
        -sdk iphonesimulator
        -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest'

    - name: Test ObjectDetector
      working-directory: ./object_detection
      run: >-
        xcodebuild test
        -workspace ObjectDetector.xcworkspace
        -scheme ObjectDetector
        -sdk iphonesimulator
        -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest'

    # --- UPLOAD THE BUILT APP ---
    # This step only runs if the build and tests succeed.
    - name: Upload App Artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ObjectDetectorApp
        path: image_classification/DerivedData/Build/Products/Debug-iphonesimulator/ObjectDetector.app

    # --- UPLOAD THE TEST RESULTS ---
    # This step runs REGARDLESS of whether the tests passed or failed.
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ObjectDetectorTestResults
        path: /Users/runner/Library/Developer/Xcode/DerivedData/ObjectDetector-*/Logs/Test/*.xcresult

  # # --- Job for the FaceDetector project ---
  # face-detector:
  #   name: Build and Test FaceDetector
  #   runs-on: macos-latest

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v4

  #   - name: Download models
  #     working-directory: ./face_detector
  #     run: ./RunScripts/download_models.sh
      
  #   - name: Install CocoaPods
  #     working-directory: ./face_detector
  #     run: pod install

  #   - name: Build FaceDetector
  #     working-directory: ./face_detector
  #     run: >-
  #       xcodebuild build
  #       -workspace FaceDetector.xcworkspace
  #       -scheme FaceDetector
  #       -sdk iphonesimulator
  #       -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest'

  #   - name: Test FaceDetector
  #     working-directory: ./face_detector
  #     run: >-
  #       xcodebuild test
  #       -workspace FaceDetector.xcworkspace
  #       -scheme FaceDetector
  #       -sdk iphonesimulator
  #       -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest'
