# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "testing/joshua" ]
  pull_request:
    branches: [ "testing/joshua" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./image_classification
      run: xcodebuild build -scheme ImageClassifier -sdk iphonesimulator
    - name: Run tests
      working-directory: ./image_classification
      run: xcodebuild test -scheme ImageClassifier -sdk iphonesimulator
